version: '3.8'

networks:
  items.backend:
    driver: bridge

services:
  app:
    container_name: ecs-practice.items.app
    build: ./app
    image: ecs-practice/items
    ports:
      - 3030:3030
    networks:
      - items.backend
